config/routes.rb
Rails.application.routes.draw do
  resources :join_table_user_to_carts
  resources :carts, path: 'mon_panier'
  root "items#index"
  devise_for :users

  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :join_table_user_to_carts
    has_many :items, through: :join_table_user_to_carts
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    @items = @cart.items
    @total_price = total_price
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    set_item
    if @cart.added_items << @item
      flash[:success] = "Element ajouté à votre panier"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def total_price
      total = 0
      @cart.items.each do |item|
        total += item.price
      end
      return total
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
        <div class="px-4 sm:px-6 lg:px-8 py-8 w-full">

            <!-- Page content -->
            <div class="max-w-5xl mx-auto flex flex-col lg:flex-row lg:space-x-8 xl:space-x-16">

                <!-- Cart items -->
                <div class="mb-6 lg:mb-0">
                    <header class="mb-2">
                        <!-- Title -->
                        <h1 class="text-2xl md:text-3xl text-slate-800 font-bold">Shopping Cart (<%= @cart.items.count %>) ✨</h1>
                    </header>

                    <ul>
                        <!-- Cart item -->
                        <% @cart.items.each do |item| %>
                        <li class="sm:flex items-center py-6 border-b border-slate-200">
                            <div class="block mb-4 sm:mb-0 mr-5 md:w-32 xl:w-auto shrink-0" style="width: 200px; height: 142px">
                                <%= image_tag item.image_url, class: "rounded-sm", alt: "Photo de chat"%>
                            </div>
                            <div class="grow">
                                <h3 class="text-lg font-semibold text-slate-800 mb-1"><%= item.title %></h3>
                                <div class="text-sm mb-2"><%= item.description %></div>
                                <!-- Product meta -->
                                <div class="flex flex-wrap justify-between items-center">
                                    <!-- Rating and price -->
                                    <div class="flex flex-wrap items-center space-x-2 mr-2">
                                        <!-- Price -->
                                        <div>
                                            <div class="inline-flex text-sm font-medium bg-emerald-100 text-emerald-600 rounded-full text-center px-2 py-0.5"><%= '%.2f' % item.price %> €</div>
                                        </div>
                                    </div>
                                    <button class="text-sm underline hover:no-underline">Remove</button>
                                </div>
                            </div>
                        </li>
                        <% end %>
                    </ul>

                    <div class="mt-6 text-center lg:text-left">
                        <%= link_to root_path do %>
                        <span class="text-sm font-medium text-indigo-500 hover:text-indigo-600">&lt;- Back To Shopping</span>
                        <% end %>
                    </div>

                </div>

                <!-- Sidebar -->
                <div class="max-w-sm mx-auto lg:max-w-none">
                    <div class="bg-white p-5 shadow-lg rounded-sm border border-slate-200 lg:w-72 xl:w-80">
                        <div class="text-slate-800 font-semibold mb-2">Order Summary</div>
                        <!-- Order details -->
                        <ul class="mb-4">
                            <li class="text-sm w-full flex justify-between py-3 border-b border-slate-200">
                                <div>Products &amp; Subscriptions</div>
                                <div class="font-medium text-slate-800"><%= '%.2f' % @total_price %> €</div>
                            </li>
                        </ul>
                        <!-- Promo box -->
                        <div class="mb-4">
                            <%= form_tag checkout_create_path, method: :post, data: { turbo: false } do %>
                                <input type="hidden" name="total" value="<%= @total_price %>" />
                                <%= submit_tag "Buy Now -  #{'%.2f' % @total_price}  €", class: "btn w-full bg-indigo-500 hover:bg-indigo-600 text-white" %>
                            <% end %>
                        </div>
                        <div class="text-xs text-slate-500 italic text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do <a class="underline hover:no-underline" href="#0">Terms</a>.</div>
                    </div>
                </div>

            </div>

        </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div class="px-4 sm:px-6 lg:px-8 py-8 w-full">
  <p style="color: green"><%= notice %></p>
  
  <%= render @cart %>
  
  <div>
    <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
    <%= link_to "Back to carts", carts_path %>
    
    <%= button_to "Destroy this cart", @cart, method: :delete %>
  </div>
</div>