config/routes.rb
Rails.application.routes.draw do
  resources :join_table_user_to_carts
  resources :carts, path: 'mon_panier'
  root "items#index"
  devise_for :users

  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :join_table_user_to_carts
    has_many :carts, through: :join_table_user_to_carts
    
    has_many :orders

    validates :title, presence: true, length: {in: 3..100, message: "Title lenght must be between 3 and 100" }
    validates :description, presence: true, length: {in: 10..500, message: "Description lenght must be between 10 and 500" }
    validates :price, presence: true, numericality: {greater_than: 0, message: "Price must be positive"}
    validates :image_url, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
    @items = Item.all.sample(3)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {})
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="col-span-full md:col-span-6 xl:col-span-4 bg-white shadow-lg rounded-sm border border-slate-200 overflow-hidden" id="<%= dom_id item %>">
    <%= link_to item_path(item.id) do %>
    <div class="flex flex-col h-full">
        <div class="relative">
            <%= image_tag item.image_url, class: "w-full", alt: "Photo de chat", style: "width=301 height=226"%>
        </div>
        <div class="grow flex flex-col p-5">
            <div class="grow">
                <header class="mb-2">
                    <h3 class="text-lg text-slate-800 font-semibold mb-1"><%=item.title%></h3>
                    <div class="text-sm"><%=item.description%></div>
                </header>
            </div>
            <div class="flex flex-wrap justify-between items-center">
                <div>
                    <div class="inline-flex text-sm font-medium bg-emerald-100 text-emerald-600 rounded-full text-center px-2 py-0.5"><%= '%.2f' % item.price%> €</div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editer la fiche</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Afficher la fiche en détail", @item %> |
  <%= link_to "Revenir en arrière", items_path %>
</div>

app/views/items/index.html.erb
<div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">
  <p style="color: green"><%= notice %></p>
  
  <div id="items" class="grid grid-cols-12 gap-6">
    <% @items.each do |item| %>
    <%= render item %>
    <% end %>
  </div>
</div>

app/views/items/index1.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listes des chats ici bas (surêment à supprimer pour le vrai front)</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p><%= link_to "Intéressé(e) ? Plus d'information ici", item %></p>
    <p>Ajouter au panier (Link to à faire plus tard)</p>
  <% end %>
</div>


<ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>

        <li>
          Voici ton email : <%= current_user.email %>
        </li>

        <li>
          <%= link_to "Edit email / password", edit_user_registration_path %>
        </li>

      <% else %>
        <li>    
          <%= link_to "Sign in", new_user_session_path %>
        </li>

        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>

      <% end %>
    </ul>

app/views/items/new.html.erb
<h1>Créer une nouvelle fiche</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Revenir en arrière", items_path %>
</div>

app/views/items/show.html.erb
<div class="px-4 sm:px-6 lg:px-8 py-8 w-full">
  <div class="max-w-5xl mx-auto flex flex-col lg:flex-row lg:space-x-8 xl:space-x-16">
    
    <!-- Content -->
    <div>
      <div class="mb-3">
        <%= link_to "<- Back To Listing", root_path, class: "text-sm font-medium text-indigo-500 hover:text-indigo-600" %>
      </div>
      <div class="mb-4">
        <!-- Title -->
        <h1 class="text-2xl md:text-3xl text-slate-800 font-bold mb-2"><%=@item.title%></h1>
        <p><%=@item.description%></p>
      </div>
      <!-- Image -->
      <figure class="mb-6">
        <%= image_tag @item.image_url, class: "w-full rounded-sm", alt: "Photo de chat", style: "width=640 height=360"%>
      </figure>
      <%= form_with(url: join_table_user_to_carts_path, method: :post) do |f| %>
        <%= f.hidden_field :id, value: @item.id %>
        <%= f.submit "Ajouter au panier - #{'%.2f' % @item.price}€", class: "btn w-full bg-indigo-500 hover:bg-indigo-600 text-white" %>
      <% end %>
      <hr class="my-6 border-t border-slate-200">
      
      <!-- Related -->
      <div>
        <h2 class="text-xl leading-snug text-slate-800 font-bold mb-2">Frequently Bought Together</h2>
        <ul class="space-y-8 sm:space-y-5 my-6">
          <% @items.each do |item| %>
          <!-- Related item -->
          <li class="sm:flex items-center">
            <div class="block mb-4 sm:mb-0 mr-5 md:w-32 xl:w-auto shrink-0">
              <%= link_to item_path(item.id) do %>
                <%= image_tag item.image_url, class: "rounded-sm", alt: "Photo de chat", style: "width=200 height=142"%>
              <% end %>
            </div>
            <div class="grow">
              <%= link_to item_path(item.id) do %>
                <h3 class="text-lg font-semibold text-slate-800 mb-1"><%= item.title %></h3>
              <% end %>
              <div class="text-sm mb-2"><%= item.description %></div>
              <!-- Rating and price -->
              <div class="flex flex-wrap items-center space-x-2">
                <!-- Price -->
                <div>
                  <div class="inline-flex text-sm font-medium bg-emerald-100 text-emerald-600 rounded-full text-center px-2 py-0.5"><%= '%.2f' % item.price %>€</div>
                </div>
              </div>
            </div>
            <p>coucou Sarah</p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>    
  </div>
  

  
</div>
  
  