config/routes.rb
Rails.application.routes.draw do
  resources :join_table_user_to_carts
  resources :carts, path: 'mon_panier'
  root "items#index"
  devise_for :users

  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/join_table_user_to_cart.rb
class JoinTableUserToCart < ApplicationRecord
    belongs_to :cart
    belongs_to :item
    has_many :users, through: :carts
end

app/controllers/join_table_user_to_carts_controller.rb
class JoinTableUserToCartsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_join_table_user_to_cart, only: %i[ show edit update destroy ]

  # GET /join_table_user_to_carts or /join_table_user_to_carts.json
  def index
    @join_table_user_to_carts = JoinTableUserToCart.all
  end

  # GET /join_table_user_to_carts/1 or /join_table_user_to_carts/1.json
  def show
  end

  # GET /join_table_user_to_carts/new
  def new
    @join_table_user_to_cart = JoinTableUserToCart.new
  end

  # GET /join_table_user_to_carts/1/edit
  def edit
  end

  # POST /join_table_user_to_carts or /join_table_user_to_carts.json
  def create
    @itemToAdd = JoinTableUserToCart.new(cart_id: current_user.cart.id, item_id: params[:id])

      if @itemToAdd.save
        redirect_to cart_path(current_user.cart.id)
      else

      end
  end

  # PATCH/PUT /join_table_user_to_carts/1 or /join_table_user_to_carts/1.json
  def update
    respond_to do |format|
      if @join_table_user_to_cart.update(join_table_user_to_cart_params)
        format.html { redirect_to join_table_user_to_cart_url(@join_table_user_to_cart), notice: "Join table user to cart was successfully updated." }
        format.json { render :show, status: :ok, location: @join_table_user_to_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @join_table_user_to_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /join_table_user_to_carts/1 or /join_table_user_to_carts/1.json
  def destroy
    @join_table_user_to_cart.destroy

    respond_to do |format|
      format.html { redirect_to join_table_user_to_carts_url, notice: "Join table user to cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join_table_user_to_cart
      @join_table_user_to_cart = JoinTableUserToCart.find(params[:id])
    end
end

app/helpers/join_table_user_to_carts_helper.rb
module JoinTableUserToCartsHelper
end

app/views/join_table_user_to_carts/_form.html.erb
<%= form_with(model: join_table_user_to_cart, class: "contents") do |form| %>
  <% if join_table_user_to_cart.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(join_table_user_to_cart.errors.count, "error") %> prohibited this join_table_user_to_cart from being saved:</h2>

      <ul>
        <% join_table_user_to_cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/join_table_user_to_carts/_join_table_user_to_cart.html.erb
<div id="<%= dom_id join_table_user_to_cart %>">
  <% if action_name != "show" %>
    <%= link_to "Show this join table user to cart", join_table_user_to_cart, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this join table user to cart', edit_join_table_user_to_cart_path(join_table_user_to_cart), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/join_table_user_to_carts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing join table user to cart</h1>

  <%= render "form", join_table_user_to_cart: @join_table_user_to_cart %>

  <%= link_to "Show this join table user to cart", @join_table_user_to_cart, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to join table user to carts", join_table_user_to_carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/join_table_user_to_carts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Join table user to carts</h1>
    <%= link_to 'New join table user to cart', new_join_table_user_to_cart_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="join_table_user_to_carts" class="min-w-full">
    <%= render @join_table_user_to_carts %>
  </div>
</div>

app/views/join_table_user_to_carts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New join table user to cart</h1>

  <%= render "form", join_table_user_to_cart: @join_table_user_to_cart %>

  <%= link_to 'Back to join table user to carts', join_table_user_to_carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/join_table_user_to_carts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @join_table_user_to_cart %>

    <%= link_to 'Edit this join_table_user_to_cart', edit_join_table_user_to_cart_path(@join_table_user_to_cart), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this join_table_user_to_cart', join_table_user_to_cart_path(@join_table_user_to_cart), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to join_table_user_to_carts', join_table_user_to_carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>