config/routes.rb
Rails.application.routes.draw do
  resources :join_table_user_to_carts
  resources :carts, path: 'mon_panier'
  root "items#index"
  devise_for :users

  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetChats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script scr=""https://js.stripe.com/v3"></script>
  </head>

  <body>
    <header class="sticky top-0 bg-white border-b border-slate-200 z-30">
      <div class="px-4 sm:px-6 lg:px-8">
          <div class="flex items-center justify-between h-16 -mb-px">
              <div class="flex">
                <%= link_to root_path do %>
                <span class="ml-2 font-bold">AdopteUnChaton</span>
                <% end %>
              </div>
              <div class="flex items-center space-x-3">
                <% if user_signed_in? %>
                  <%= link_to cart_path(current_user.cart.id), class: "w-8 h-8 flex items-center justify-center bg-slate-100 hover:bg-slate-200 rounded-full" do %>
                    <span class="sr-only">Search</span>
                    <svg class="w-4 h-4" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                        <path class="fill-current text-slate-500" d="M4.5,16c-0.42,0-0.77-0.15-1.06-0.44C3.15,15.27,3,14.92,3,14.5s0.15-0.77,0.44-1.06C3.73,13.15,4.08,13,4.5,13
                        s0.77,0.15,1.06,0.44C5.85,13.73,6,14.08,6,14.5s-0.15,0.77-0.44,1.06C5.27,15.85,4.92,16,4.5,16z M13.5,16
                        c-0.42,0-0.77-0.15-1.06-0.44C12.15,15.27,12,14.92,12,14.5s0.15-0.77,0.44-1.06C12.73,13.15,13.08,13,13.5,13s0.77,0.15,1.06,0.44
                        C14.85,13.73,15,14.08,15,14.5s-0.15,0.77-0.44,1.06C14.27,15.85,13.92,16,13.5,16z M4.27,3.5L6,7.5h6.27l1.71-4H4.27z M3.62,2H15.5
                        c0.19,0,0.34,0.08,0.43,0.23s0.1,0.31,0.03,0.48l-2.31,5.38c-0.13,0.28-0.31,0.5-0.55,0.67C12.85,8.92,12.58,9,12.27,9H5.6
                        l-0.88,1.5H15V12H4.75c-0.6,0-1.04-0.25-1.32-0.75s-0.28-1,0.01-1.5l1.08-1.88L1.79,1.5H0V0h2.77L3.62,2z M6,7.5h6.27H6z"></path>
                    </svg>
                  <% end %>       
                  <hr class="w-px h-6 bg-slate-200">
                  <div class="relative inline-flex" x-data="{ open: false }">
                      <button class="inline-flex justify-center items-center group" aria-haspopup="true" @click.prevent="open = !open" :aria-expanded="open" aria-expanded="false">
                          <div class="flex items-center truncate">
                              <span class="truncate ml-2 text-sm font-medium group-hover:text-slate-800">Mon compte</span>
                              <svg class="w-3 h-3 shrink-0 ml-1 fill-current text-slate-400" viewBox="0 0 12 12">
                                  <path d="M5.9 11.4L.5 6l1.4-1.4 4 4 4-4L11.3 6z"></path>
                              </svg>
                          </div>
                      </button>
                      <div class="origin-top-right z-10 absolute top-full right-0 min-w-44 bg-white border border-slate-200 py-1.5 rounded shadow-lg overflow-hidden mt-1" @click.outside="open = false" @keydown.escape.window="open = false" x-show="open" x-transition:enter="transition ease-out duration-200 transform" x-transition:enter-start="opacity-0 -translate-y-2" x-transition:enter-end="opacity-100 translate-y-0" x-transition:leave="transition ease-out duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" style="display: none;">
                          <div class="pt-0.5 pb-2 px-3 mb-1 border-b border-slate-200">
                              <div class="font-medium text-slate-800"><%= current_user.email %></div>
                              <% if current_user.is_admin == true %>
                                <div class="text-xs text-slate-500 italic">Administrateur</div>
                              <% end %>
                          </div>
                          <ul>
                              <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "font-medium text-sm text-indigo-500 hover:text-indigo-600 flex items-center py-1 px-3" %></li>
                          </ul>                
                      </div>
                  </div>
                <% else %>
                    <%= link_to "Sign in", new_user_session_path, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white" %>
                    <%= link_to "Sign up", new_user_registration_path, class: "btn border-slate-200 hover:border-slate-300 text-indigo-500" %>
                <% end %>
              </div>
          </div>
      </div>
    </header>
    <main>
        <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </main>
    <footer class="pb-2 bg-white rounded-lg shadow md:px-6 md:pb-8">
      <hr class="mb-6 border-gray-200 sm:mx-auto lg:mb-8"/>
      <span class="block text-sm text-gray-500 sm:text-center">© 2022 AdopteUnChaton™. All Rights Reserved.</span>
    </footer>
  </body>
</html>